version: "3.8"
services:
  ewm-stats-database:
    image: postgres:15.1-alpine
    container_name: ewm-stats-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

  ewm-stats-server:
    build: ewm-stats-service/ewm-stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-database:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev

  ewm-main-database:
    image: postgres:15.1-alpine
    container_name: ewm-main-database
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

  ewm-main-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-stats-server
      - ewm-main-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-database:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
      - EWM_STATS_SERVER_URI=http://ewm-stats-server:9090
