version: "3.8"
services:
  ewm-stats-server:
    build: ewm-stats-service/ewm-stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-database:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev

  ewm-stats-database:
    image: postgres:15.1-alpine
    container_name: ewm-stats-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
